---

skip_list:
  - "204"
  - "505"

# exclude_paths:
#   - ./my/excluded/directory/
#   - ./my/other/excluded/directory/
#   - ./last/excluded/directory/
# parseable: true
# quiet: true
# rulesdir:
#   - ./rule/directory/
# tags:
#   - run_this_tag
# use_default_rules: true
# verbosity: 1
